#!/bin/bash
cd ~ || return

# Log WLR errors and logs to the hyprland log
export HYPRLAND_LOG_WLR=1

# Tell XWayland to use a cursor theme
export XCURSOR_THEME=Sweet-cursors

# Set a cursor size
export XCURSOR_SIZE=24

# IME Support: fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
export SDL_IM_MODULE=fcitx5
export GLFW_IM_MODULE=fcitx5

# Enables automatic scaling, based on the monitor’s pixel density
export QT_AUTO_SCREEN_SCALE_FACTOR=1
# Tell QT applications to use the Wayland backend, and fall back to x11 if Wayland is unavailable
export QT_QPA_PLATFORM="wayland;xcb"
# Disables window decorations on QT applications
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
# Tells QT based applications to pick your theme from qt5ct, use with Kvantum
export QT_QPA_PLATFORMTHEME=qt5ct
# Run SDL2 applications on Wayland
export SDL_VIDEODRIVER=wayland
# Fix possibly broken Java applications
export _JAVA_AWT_WM_NONEREPARENTING=1
# Clutter package already has wayland enabled, this variable will force Clutter applications to try and use the Wayland backend
export CLUTTER_BACKEND="wayland"
# Force backend for wayland-enabled GTK3 and GTK4 backends
export GDK_BACKEND="wayland,x11"

sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/libexec/xdg-desktop-portal-hyprland &
sleep 2
/usr/libexec/xdg-desktop-portal &
